### ISSUE TITLE
I encountered some problems when trying to run the code

### ISSUE THREAD

**Issue by Craw-B** [denniskb/spice#1]
I downloaded the code to run on the server.

mkdir build & cd build
cmake ..

Get executable samples , but when i try to run
./samples --model brunel --nsyn 1234 --gpu single --bench sim

Prompt error

Usage: spice_bench.exe {brunel|brunel+|vogels} [synapse-count] [iter-count]

i want to know what is the spice_bench.exe,and How do I run successfully。 thanks！

**Comment by denniskb** [comment]
Inside the samples/ folder you'll find 2 files, "main.cpp" and "main2.cpp". Delete " main.cpp" and rename "main2.cpp"&rarr;"main.cpp" and everything should be working fine.
